services:
  carbonio-user-management:
    build:
      context: ./carbonio-user-management
      dockerfile: Dockerfile
    container_name: carbonio-user-management
    network_mode: "host"
    volumes:
      - ../../boot/target:/app
    restart: on-failure
    environment:
      - MAILBOX_HOST=127.0.0.1
      - MAILBOX_PORT=8080
      - MAILBOX_PROTOCOL=http