<?xml version="1.0" encoding="UTF-8"?>

<!--
SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com>

SPDX-License-Identifier: AGPL-3.0-only
-->

<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://maven.apache.org/POM/4.0.0"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>

  <licenses>
    <license>
      <comments>Copyright (C) 2022 Zextras, https://www.zextras.com</comments>
      <name>AGPL-3.0-only</name>
    </license>
  </licenses>

  <groupId>com.zextras.carbonio.user-management</groupId>
  <artifactId>carbonio-user-management</artifactId>
  <version>${revision}${changelist}</version>
  <packaging>pom</packaging>

  <name>carbonio-user-management</name>
  <url>https://www.github.com/Zextras/carbonio-user-management</url>

  <modules>
    <module>sdk</module>
    <module>app</module>
  </modules>

  <properties>
    <!-- Maven CI Friendly -->
    <revision>1.2.4</revision>
    <changelist>-1</changelist>

    <!-- Dependencies -->
    <assertj.version>3.27.7</assertj.version>
    <carbonio-mailbox-sdk.version>1.18.0</carbonio-mailbox-sdk.version>
    <carbonio-quarkus-extensions.version>1.11.2-1</carbonio-quarkus-extensions.version>

    <!-- Plugins -->
    <maven-compiler-plugin.version>3.15.0</maven-compiler-plugin.version>
    <maven-failsafe.version>3.5.6</maven-failsafe.version>
    <maven-jacoco.version>0.8.15</maven-jacoco.version>
    <maven-jar-plugin.version>3.5.0</maven-jar-plugin.version>
    <maven-surefire.version>3.5.6</maven-surefire.version>
    <maven-resources-plugin.version>3.5.0</maven-resources-plugin.version>

    <!-- Other properties -->
    <maven.compiler.source>21</maven.compiler.source>
    <maven.compiler.target>21</maven.compiler.target>
    <maven.version.ignore>(?i).*-(alpha|beta|m|rc)([-.]?\d+)?</maven.version.ignore>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

    <!-- Flags to skip/run tests and the report generation -->
    <skip.integration.tests>true</skip.integration.tests>
    <skip.unit.tests>true</skip.unit.tests>
    <skip.jacoco.full.report.generation>true</skip.jacoco.full.report.generation>
  </properties>

  <dependencyManagement>
    <dependencies>
      <!-- Mailbox -->
      <dependency>
        <groupId>com.zextras</groupId>
        <artifactId>carbonio-mailbox-sdk</artifactId>
        <version>${carbonio-mailbox-sdk.version}</version>
      </dependency>

      <!-- Test dependencies (not managed by Quarkus BOM) -->
      <dependency>
        <groupId>org.assertj</groupId>
        <artifactId>assertj-core</artifactId>
        <version>${assertj.version}</version>
        <scope>test</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-jar-plugin</artifactId>
          <version>${maven-jar-plugin.version}</version>
        </plugin>

        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-resources-plugin</artifactId>
          <version>${maven-resources-plugin.version}</version>
        </plugin>

        <plugin>
          <groupId>org.codehaus.mojo</groupId>
          <artifactId>flatten-maven-plugin</artifactId>
          <version>1.7.3</version>
          <configuration>
              <updatePomFile>true</updatePomFile>
              <flattenMode>resolveCiFriendliesOnly</flattenMode>
          </configuration>
          <executions>
              <execution>
                  <id>flatten</id>
                  <phase>process-resources</phase>
                  <goals>
                      <goal>flatten</goal>
                  </goals>
              </execution>
              <execution>
                  <id>flatten.clean</id>
                  <phase>clean</phase>
                  <goals>
                      <goal>clean</goal>
                  </goals>
              </execution>
          </executions>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>

  <distributionManagement>
    <snapshotRepository>
      <id>zextras-java-sdk</id>
      <name>Zextras private repository</name>
      <url>https://zextras.jfrog.io/artifactory/maven-snapshot</url>
    </snapshotRepository>
    <repository>
      <id>zextras-java-sdk</id>
      <name>Zextras private repository</name>
      <url>https://zextras.jfrog.io/artifactory/public-maven-repo</url>
    </repository>
  </distributionManagement>

  <repositories>
    <repository>
      <id>zextras-java-sdk</id>
      <name>Zextras public maven repo</name>
      <url>https://zextras.jfrog.io/artifactory/java-sdk</url>
    </repository>
  </repositories>

</project>
