carbonio.service.name=carbonio-user-management

networking-config.carbonio.service.host=127.78.0.5
networking-config.carbonio.service.port=10000

networking-config.carbonio.service-discover.host=127.0.0.1
networking-config.carbonio.service-discover.port=8500

networking-config.carbonio.mailbox.host=127.78.0.5
networking-config.carbonio.mailbox.port=20000

networking-config.carbonio.postgresql.host=127.78.0.5
networking-config.carbonio.postgresql.port=5432

application-config.cache.userinfo-ttl=43200
application-config.cache.usermyself-ttl=

quarkus.package.jar.type=uber-jar
quarkus.hibernate-orm.mapping.format.global=ignore

# ------------------------------------------------------------

%test.quarkus.compose.devservices.enabled=false
%test.networking-config.carbonio.service.host=localhost

# ------------------------------------------------------------

# Config for devmode (runs docker dependencies and then quarkus app with mvn -pl app quarkus:dev)
%dev.quarkus.datasource.devservices.enabled=false
%dev.quarkus.datasource.db-kind=postgresql
%dev.quarkus.compose.devservices.files=../docker/devmode/compose-devservices.yml
%dev.networking-config.carbonio.service.host=localhost
%dev.networking-config.carbonio.service.port=10000
%dev.quarkus.http.port=10000
%dev.networking-config.carbonio.service-discover.host=localhost
%dev.networking-config.carbonio.service-discover.port=8500
%dev.networking-config.carbonio.mailbox.host=localhost
%dev.networking-config.carbonio.mailbox.port=20000
%dev.networking-config.carbonio.postgresql.host=localhost
%dev.networking-config.carbonio.postgresql.port=5432