# SPDX-FileCopyrightText: 2026 2026 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: AGPL-3.0-only

carbonio.service.name=carbonio-user-management

networking-config.carbonio.service.host=127.78.0.5
networking-config.carbonio.service.port=10000

networking-config.carbonio.service-discover.host=127.0.0.1
networking-config.carbonio.service-discover.port=8500

networking-config.carbonio.mailbox.host=127.78.0.5
networking-config.carbonio.mailbox.port=20000

application-config.cache.userinfo-ttl=43200

quarkus.package.jar.type=uber-jar
quarkus.smallrye-openapi.servers=http://localhost:10000

# ------------------------------------------------------------

%test.quarkus.compose.devservices.enabled=false
%test.quarkus.devservices.enabled=false
%test.quarkus.test.arg-line=--enable-preview --enable-native-access=ALL-UNNAMED
%test.networking-config.carbonio.service.host=localhost

# ------------------------------------------------------------

# Config for devmode (runs docker dependencies and then quarkus app with mvn -pl app quarkus:dev)
%dev.quarkus.compose.devservices.files=../docker/devmode/compose-devservices.yml
%dev.networking-config.carbonio.service.host=localhost
%dev.networking-config.carbonio.service.port=10000
%dev.quarkus.http.port=10000
%dev.networking-config.carbonio.service-discover.host=localhost
%dev.networking-config.carbonio.service-discover.port=8500
%dev.networking-config.carbonio.mailbox.host=localhost
%dev.networking-config.carbonio.mailbox.port=20000
quarkus.analytics.disabled=false
