# SPDX-FileCopyrightText: 2026 Zextras <https://www.zextras.com>
#
# SPDX-License-Identifier: AGPL-3.0-only

# Migration mappings: old-key=new-key
# Renames keys in /etc/carbonio/user-management/config.properties
carbonio.user-management.host=carbonio.service.host
carbonio.user-management.port=carbonio.service.port
