// SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com>
//
// SPDX-License-Identifier: AGPL-3.0-only

syntax = "proto3";

option java_multiple_files = true;
option java_package = "com.zextras.carbonio.user_management.sdk.grpc";

package usermanagement;

service UserManagementService {
  rpc GetUserMyself (GetUserMyselfRequest) returns (UserMyselfResponse);
  rpc GetUserById (GetUserByIdRequest) returns (UserInfoResponse);
  rpc GetUserByEmail (GetUserByEmailRequest) returns (UserInfoResponse);
  rpc GetUsers (GetUsersRequest) returns (GetUsersResponse);
}

enum UserTypeProto {
  INTERNAL = 0;
  GUEST = 1;
}

message UserInfoProto {
  string user_id = 1;
  string email = 2;
  string full_name = 3;
  string domain = 4;
  string status = 5;
  UserTypeProto type = 6;
}

message UserMyselfProto {
  UserInfoProto info = 1;
  string locale = 2;
  map<string, bool> feature_list = 3;
}

message GetUserMyselfRequest {
  string token = 1;
}

message GetUserByIdRequest {
  string token = 1;
  string user_id = 2;
}

message GetUserByEmailRequest {
  string token = 1;
  string user_email = 2;
}

message GetUsersRequest {
  string token = 1;
  repeated string user_ids = 2;
}

message GetUsersResponse {
  repeated UserInfoProto users = 1;
}

message UserInfoResponse {
  UserInfoProto user = 1;
}

message UserMyselfResponse {
  UserMyselfProto user = 1;
}
