services:
  soap-mock:
    image: mockserver/mockserver:5.15.0
    container_name: soap-mock
    ports:
      - "127.0.0.1:7070:8000"
    volumes:
      - ./mockserver/soap.json:/config/soap.json
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/soap.json
    command: -serverPort 8000 -logLevel WARN

  carbonio-user-management:
    build:
      context: ./carbonio-user-management
      dockerfile: Dockerfile
    container_name: carbonio-user-management
    network_mode: "host"
    volumes:
      - ../../boot/target:/app
    depends_on:
      - soap-mock
    restart: on-failure
